### ISSUE TITLE
Panic in webscokets

### ISSUE THREAD

**Issue by mr-tron** [Kucoin/kucoin-go-sdk#111]
```
panic: send on closed channel
        panic: close of closed channel

goroutine 467 [running]:
github.com/Kucoin/kucoin-go-sdk.(*WebSocketClient).read.func1(0xc000510600)
        /home/user/prog/gopath/pkg/mod/github.com/!kucoin/kucoin-go-sdk@v1.2.10/websocket.go:248 +0x2f
panic(0xa972c0, 0xc18420)
        /home/user/prog/gopath/go1.16/src/runtime/panic.go:965 +0x1b9
github.com/Kucoin/kucoin-go-sdk.(*WebSocketClient).read(0xc000510600)
        /home/user/prog/gopath/pkg/mod/github.com/!kucoin/kucoin-go-sdk@v1.2.10/websocket.go:271 +0x149
created by github.com/Kucoin/kucoin-go-sdk.(*WebSocketClient).Connect
        /home/user/prog/gopath/pkg/mod/github.com/!kucoin/kucoin-go-sdk@v1.2.10/websocket.go:240 +0x572
```
I think it's reproduces on closing connection from server side

**Comment by iamalanal** [comment]
Is the issue solved?

**Comment by mr-tron** [comment]
didn't use it for few years.
